# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step to check Node.js version
- script: |
    node -v
  displayName: 'Check Node.js Version'
- task: terraform-summary-pr-commenter-task@1
  inputs:
    ADO_STAGE_NAME: 'test'
    ADO_STAGE_LINK: 'test'
    ADO_JOB_LINK: 'test'
    GITHUB_TOKEN: $(GITHUB_TOKEN)
    GITHUB_OWNER: 'tj-0-tj'
    GITHUB_REPO: 'tf-rnd-azure-modules'
    GITHUB_ISSUE_NUMBER: '5'
    ENVIRONMENT: 'DEV'
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
