# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# Step to check Node.js version
- script: |
    node -v
  displayName: 'Check Node.js Version'

# Step to check installed npm modules
- script: |
    npm list
  displayName: 'Check Installed npm Modules'
  
- task: terraformsummaryprcommentertask@1
  inputs:
    ADO_STAGE_NAME: 'test'
    ADO_STAGE_LINK: 'test'
    ADO_JOB_LINK: 'test'
    GITHUB_TOKEN: 'test'
    GITHUB_OWNER: 'test'
    GITHUB_REPO: 'test'
    GITHUB_ISSUE_NUMBER: 'test'
    ENVIRONMENT: 'DEV'
  
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
